apiVersion: v1
kind: Service
metadata:
  name: mymavenapp
  labels:
    app: mymavenapp
spec:
  type: NodePort  
  ports:
    - port: 8200 
      targetPort: 8200 
      protocol: TCP
  selector:
    app: mymavenapp
